name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: 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
          deploy-branch: gh-pages
